http.host: "0.0.0.0"
config.reload.automatic: true
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
# turn on slow log to find some peformence problem
slowlog.threshold.warn: 2s
slowlog.threshold.info: 1s
slowlog.threshold.debug: 500ms
slowlog.threshold.trace: 100ms