version: '2'
services:

  elasticsearch:
    #build: ./elasticsearch
    #image: elasticsearch_with_exporter:7.8.1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elasticsearch
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - /data/volumes/ops/elasticsearch:/usr/share/elasticsearch/data
      - ./ssl:/opt/ssl
    network_mode: host

  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.1
    container_name: logstash
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - /data/logs:/data/logs
    network_mode: host

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kibana
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
      - ./kibana/plugins/:/opt/kibana/plugins/
    network_mode: host
