logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

filebeat.config.inputs:
  enabled: true
  path: inputs.d/*.yml
  reload.enabled: true
  reload.period: 10s

output.logstash:
  hosts: ["logstash:5066"]
  loadbalance: true
  ssl.certificate_authorities: ["/etc/filebeat/ssl/filebeat/ca.pem"]
  ssl.certificate: "/etc/filebeat/ssl/filebeat/filebeat.crt"
  ssl.key: "/etc/filebeat/ssl/filebeat/filebeat.key"